### ISSUE TITLE
External Database

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [sheshbabu/freshlytics#9]
I am unable to connect to an external database from freshlytics

```yml
version: "3"

networks:
  web:
    external: true

services:
  freshlytics:
    image: freshlytics/freshlytics
    command: npm start
    container_name: Analytics
    networks:
      - web
    ports:
      - "80:3001"
    environment:
      - DATABASE_URL=postgresql://dbuser:dbuser-password@dbhost:dbportnum/frshlytics?sslmode=require
      - NODE_ENV=production
```

Log:
```sh
Starting Analytics ... done
Attaching to Analytics
Analytics      | 
Analytics      | > freshlytics@1.0.0-beta start /app
Analytics      | > node ./dist
Analytics      | 
Analytics      | Failed to prune sessions: no pg_hba.conf entry for host "x.x.x.x", user "dbuser", database "dbname", SSL off
```
